[colors.primary]
background = "#07122E"  
foreground = "#b4befe" 

[colors.normal]
black   = "#1e1e2e"  
red     = "#f38ba8" 
green   = "#a6e3a1"
yellow  = "#f9e2af"  
blue    = "#89b4fa" 
magenta = "#cba6f7"
cyan    = "#94e2d5"  
white   = "#b4befe" 

[colors.bright]
black   = "#313244"  
yellow  = "#fab387" 
white   = "#f5c2e7"

