general.import = ["~/.config/hypr/alacritty/colors.toml", "~/.config/hypr/alacritty/fonts.toml"]

#shell = { program = "/bin/zsh", args = ["--login"] }
terminal.shell = { program = "/run/current-system/sw/bin/zsh" }

general.live_config_reload = true
general.ipc_socket = true
[env]
TERM = "alacritty"
[window]
position = "None"
dynamic_padding = true
decorations = "full"
opacity = 0.9
blur = false
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = false

[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
