#!/usr/bin/env bash
CONFIG="$HOME/.config/hypr/alacritty/alacritty.toml"

if [ "$1" == "-T" ]; then
    alacritty --config-file "$CONFIG" -e ~/tmux-sessioniser
elif [ "$1" == "-e" ]; then
    shift  # Remove the -e argument
    alacritty --config-file "$CONFIG" -e "$@"  # Pass all remaining arguments
else
    alacritty --config-file "$CONFIG"
fi
