#!/usr/bin/env bash

if [ "$1" == "-T" ]; then
    kitty -e ~/tmux-sessioniser
elif [ "$1" == "-W" ]; then # work
    shift 
    kitty -o "background=#300a24" -o "foreground=#ffffff" 
else
    kitty
fi
