#!/usr/bin/env bash


# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done




~/.config/hypr/scripts/notifications &
swww-daemon & 
swww img ~/.config/hypr/wallpapers/wallpaper2.png & 
wal -i ~/.config/hypr/wallpapers/wallpaper2.png -q -n -e -s -c &
pywalfox update &

~/.config/hypr/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &
