#!/usr/bin/env bash


LAYOUT="$HOME/.config/hypr/wlogout/layout"
STYLE="$HOME/.config/hypr/wlogout/style.css"

if [[ ! `pidof wlogout` ]]; then
    wlogout --layout ${LAYOUT} --css ${STYLE}

else
	pkill wlogout
fi
