hl.config({
	input = {
		kb_model = "",
		kb_layout = "",
		kb_variant = "",
		kb_rules = "",
		kb_file = "",

		numlock_by_default = false,
		repeat_rate = 25,
		repeat_delay = 600,
		sensitivity = 1.5,
		accel_profile = "flat",
		force_no_accel = false,
		left_handed = false,
		scroll_method = "2fg",
		scroll_button = 0,
		scroll_button_lock = 0,
		natural_scroll = false,
		follow_mouse = 1,
		mouse_refocus = true,
		float_switch_override_focus = 0,

		touchpad = {
			disable_while_typing = true,
			natural_scroll = false,
			scroll_factor = 1.0,
			middle_button_emulation = false,
			tap_button_map = "",
			clickfinger_behavior = false,
			tap_to_click = true,
			drag_lock = false,
			tap_and_drag = true,
		},
	},
})
