# example configuration

release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

port = 4242

# list of authorized tls certificate fingerprints that
# are accepted for incoming traffic
#[authorized_fingerprints]
#"bc:05:ab:7a:a4:de:88:8c:2f:92:ac:bc:b8:49:b8:24:0d:44:b3:e6:a4:ef:d7:0b:6c:69:6d:77:53:0b:14:80" = "iridium"


# define a client on the left side with IP address 192.168.178.189
[[clients]]
position = "right"
# The hostname is optional: When no hostname is specified,
# at least one ip address needs to be specified.
#hostname = "desktopdaddy"
activate_on_startup = true
# ips for ethernet and wifi
ips = ["desktopdaddy"]
# optional port
port = 4242
